$id: https://example.com/person.schema.json
$schema: https://json-schema.org/draft/2020-12/schema
$comment: This schema It defines the structure, rules, and requirements for data related to a method or process in the IDR-Schema context
title: IDR-Schema
type: object

required:
  - name

properties:
  name:
    type: string
    description: Name of the method
  short_name:
    type: string
    description: Name of the method to be used in Python
  id:
    type: string
    description: ID of the method
  description:
    type: string
    description: Description of the method
  version:
    type: string
    description: Version of the method
  type:
    type: string
    description: whether it is a process or an industry
  debug:
    type: boolean
    description: Debug mode. If true, it will print all the intermedary results

  constants:
    $comment: constants are the values that are used in the calculation of the outputs
    type: array
    items:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
          description: Name of the constant
        description:
          type: string
          description: Description of the constant
        value:
          type: number
          description: Value of the constant
        citation:
          type: string
          description: the type of the source
        source:
          type: string
          description: Source of the constant
        units:
          type: string
          description: Units of the constant

  inputs:
    $comment: inputs values of the method-n thta are used in the calculation of the outputs
    type: array
    items:
      type: object
      required:
        - name
        - value
        - from
      properties:
        name:
          type: string
          description: Name of the input
        description:
          type: string
          description: Description of the input
        value:
          anyOf:
            - type: array
              items:
                type: number
            - type: "null"
          description: Value of the input
        units:
          type: string
          description: Units of the input
        from:
          anyOf:
            - type: string
            - type: "null"
          description: Source of the input

  outputs:
    $comment: outputs are the results of the method-n that are calculated using the inputs and constants
    type: array
    items:
      type: object
      required:
        - name
        - operation
        - args
      properties:
        name:
          type: string
          description: Name of the output
        operation:
          type: string
          description: Valid sympy operation to calculate the output
        range:
          type: object
          description: Dimension of the output
          required:
            - variable
            - start
            - end
            - step
          properties:
            variable:
              type: string
              description: Variable of the output
            start:
              type: number
              description: Start of the output
            end:
              type: number
              description: End of the output
            step:
              type: number
              description: Step of the output
        args:
          type: array
          items:
            type: object
            required:
              - name
              - type
            properties:
              name:
                type: string
                description: Name of the argument
              type:
                type: string
                description:
                  defines whether the argument is a constant, input or
                  output
        description:
          type: string
          description: Description of the output
        value:
          anyOf:
            - type: number
            - type: "null"
          description: Value of the output
