name: Cement production
id: Cemento-process4-Meta
description: Meta archivo de la industria del cemento
version: 1.0.0
debug: false
constants:
  - name: limestone_demand_pre
    label: limeston demand pre
    description: limestone used in Pre
    citation: text
    source: https://www.google.com
    value: 1035
    units: Kg/p.u.
  - name: clay_demand_pre
    label: Clay demand pre
    description: Clay useed in Pre
    citation: text
    source: https://www.google.com
    value: 375
    units: Kg/p.u.
  - name: mechanical_energy_pre
    label: Mechanical energy pre
    description: Mechanical Energy  need in Pre
    citation: text
    source: https://www.google.com
    value: 115.92
    units: MJ/p.u.
  - name: water_demand_oven
    label: Water demand Oven
    description: Water used in Oven
    citation: text
    source: https://www.google.com
    value: 222
    units: l/p.u.
  - name: fuel_demand_oven
    label: fuel demand oven
    description: Fuel used in Oven
    citation: text
    source: https://www.google.com
    value: 130
    units: kg/p.u.
  - name: mechanical_energy_oven
    label: mechanical energy Oven
    description: Mechanical Energy need for SP2
    citation: text
    source: https://www.google.com
    value: 69.552
    units: MJ/p.u.
  - name: mechanical_energy_milling
    label: Mechanical energy milling
    description: Mechanical Energy need for Milling
    citation: text
    source: https://www.google.com
    value: 135.792
    units: MJ/p.u.
inputs:
  - name: cement_production
    label: Cement production
    description: Cement production
    value: [1]
    units: ton
    from: null
  - name: PM10_emission_pre
    label: PM10 Emissions Pre
    description: PM10 emission Pre
    value: null
    units: kg
    from: Cemento-process1-Pre
  - name: PM10_emission_oven
    label: PM10 emission Oven
    description: PM10 emission Oven
    value: null
    units: kg
    from: Cemento-process2-Oven
  - name: cement_emission
    label: Cement air emission Milling
    description: Cement air emission Milling
    value: null
    units: kg
    from: Cemento-process3-Milling
  - name: clinker_production_oven
    label: Clinker consumption in Pre
    description: Clinker demand by process Oven
    value: null
    units: kg
    from: Cemento-process2-Oven
  - name: CO2_emissions_oven
    label: CO2 emissions Pre
    description: CO2 emissions Oven
    value: null
    units: kg
    from: Cemento-process2-Oven
  - name: heat_losses_oven
    label: Heat Loos in Oven
    description: Heat_Loos Oven
    value: null
    units: MJ
    from: Cemento-process2-Oven
  - name: water_consumption_oven
    label: Water demand Oven
    description: Water consumption Oven
    value: null
    units: l
    from: Cemento-process2-Oven
  - name: gypsum_consumption_milling
    label: Gympsun
    description: gympsum consumption from the process milling
    value: null
    units: kg
    from: Cemento-process3-Milling
outputs:
  - name: limestone_overall_demand
    label: Limestone consumption
    operation: limestone_demand_pre * cement_production
    args:
      - name: limestone_demand_pre
        type: constants
      - name: cement_production
        type: inputs
    description: limestone consumption
    value: null
    units: kg
  - name: clay_overall_demand
    label: Clay consumption
    operation: clay_demand_pre * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: clay_demand_pre
        type: constants
    description: Clay consumption in Pre
    value: null
    units: kg
  - name: mechanical_energy_cement
    label: Mechanical energy demand
    operation: (mechanical_energy_pre + mechanical_energy_oven + mechanical_energy_milling) * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: mechanical_energy_pre
        type: constants
      - name: mechanical_energy_oven
        type: constants
      - name: mechanical_energy_milling
        type: constants
    description: Mechanical energy
    value: null
    units: kg
  - name: CO2_overall_emission
    label: CO2 emissions
    operation: CO2_emissions_oven * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: CO2_emissions_oven
        type: inputs
    description: Total C02 emissions
    value: null
    units: kg
  - name: heat_overall_losses
    label: Heat losses
    operation: heat_losses_oven * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: heat_losses_oven
        type: inputs
    description: Total Heat losses
    value: null
    units: MJ
  - name: water_consumption
    label: Water demand
    operation: water_consumption_oven  * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: water_consumption_oven
        type: inputs
    description: Total water use/loss
    value: null
    units: l
  - name: PM10_overall_emission
    label: PM10 emissions
    operation: (PM10_emission_pre + PM10_emission_oven + cement_emission) * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: PM10_emission_pre
        type: inputs
      - name: PM10_emission_oven
        type: inputs
      - name: cement_emission
        type: inputs
    description: Total PM10 emissions
    value: null
    units: kg
  - name: fuel_overall_demand * cement_production
    label: Fuel consumption
    operation: fuel_demand_oven
    args:
      - name: cement_production
        type: inputs
      - name: fuel_demand_oven
        type: constants
    description: Fuel consumption
    value: null
    units: kg
  - name: gympsum_overall_losses
    label: Gympsum losses
    operation: gypsum_consumption_milling * cement_production
    args:
      - name: cement_production
        type: inputs
      - name: gypsum_consumption_milling
        type: inputs
    description: gympsum losses from process milling
    value: null
    units: kg
